<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ftf_ftfdk"
 *
 * Auto generated by Extension Builder 2013-09-04
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'FTF.dk Templates',
	'description' => 'Templates for ftf.dk',
	'category' => 'templates',
	'author' => 'Einar Gislason',
	'author_email' => 'einarsvan@gmail.com',
	'author_company' => 'FTF',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>